let DataOverView = [
    {
        mainTitle:'Ghirardelli Company',
        bodyDescription: 'Ghirardelli \'s legacy of creating exceptional products is the result of empowering and equipping our team to take on new challenges, inspire one another and excel in all they do.',
        historyTitle:'Our History',
        historyContent:'1817 - Domenico Ghirardelli is born in Rapallo, Italy, to an exotic foods importer and his wife. At a young age, Domenico is introduced to the chocolate and confectionary trade when he apprentices with a local candy maker. 1962 - Two prominent San Franciscans acquire Ghirardelli Square and commission an architect to construct a modern specialty shopping center while retaining the exceptional Victorian qualities of the complex. 2003 - Ghirardelli introduces SQUARES stand up bags. 2006 - Ghirardelli introduces its first ecommerce initiative. 2011-Ghirardelli becomes the No. 2 baking brand in the U.S. 2016-Ghirardelli Chocolate Company celebrates its 160th anniversary.',
        titleLeft:'Learn About Chocolate',
        subTitleLeft:'How We Make Chocolate?',
        descriptionLeft:'We are one of very few American manufacturers that make chocolate starting from the cocoa bean through to finished products.',
        diffReference:'See the Ghiradelli Difference',
        src: '/images/MakeChocolate.jpg',
        titleRight:'Discover A Place', 
        descriptionRight:'Here’s a quick look at how three of our core business areas bring Ghirardelli’s products from our factories and offices to stores, shops, and restaurants across the country. \'CONFECTIONS & BAKING\'-\'RESTAURANT & RETAIL\'-\'GHIRARDELLI PROFESSIONAL PRODUCTS\' ',
        link1:'Careers',
        link2:'Contact Us',
        link3:'Global Site',
        LogoImage:'GhirardelliLogo.png',
        BannerRightImage: '/images/GhirardelliRightbar.jpg',
        BannerLeftImage:'/images/MakeChocolate.jpg',
        historyImage:'/images/GhirardelliHistory.jpg',
    },
    {
        mainTitle:'Pepsi Company',
        bodyDescription: 'We have a complementary food and beverage portfolio that includes 22 brands that in 2017 each generated more than $1 billion in estimated annual retail sales.',
        historyTitle:'Our History',
        historyContent:'PepsiCo, Inc. was established through the merger of Pepsi-Cola and Frito-Lay. Pepsi-Cola was created in the late 1890s by Caleb Bradham, a New Bern, N.C. pharmacist. Frito-Lay, Inc. was formed by the 1961 merger of the Frito Company, founded by Elmer Doolin in 1932, and the H. W. Lay Company, founded by Herman W. Lay, also in 1932. Herman Lay, former chairman and CEO of Frito-Lay, was chairman of the board of directors of the new company; Donald M. Kendall, former president and CEO of Pepsi-Cola, was president and chief executive officer. The new company reports sales of $510 million and has 19,000 employees. Major products of the new companies are: Pepsi-Cola Company',
        titleLeft:'Investors',
        subTitleLeft:'2018 Annual Report',
        descriptionLeft:'With a portfolio of iconic, beloved and locally relevant brands, we\'re delivering results today and confidently preparing for the future.',
        diffReference:'For More Information',
        src: '/images/MakeChocolate.jpg',
        titleRight:'BRANDS !!', 
        descriptionRight:'DID YOU KNOW? Pepsi-Cola brands include Pepsi, Mountain Dew, Lemon Lemon, Bubly, AMP Energy Organics, IZZE, Naked Juice, Propel, Mug, and Aquafina, among others',
        link1:'Careers',
        link2:'Contact Us',
        link3:'Global Site',
        LogoImage:'pepsiLogo.png',
        BannerRightImage: '/images/PepsiRightbar.jpg',
        BannerLeftImage:'/images/PepsiLeftbar.jpg',
        historyImage:'/images/PepsiHistory-1970.jpg',
       },
       {
        mainTitle:'Mac Cosmetic Company',
        bodyDescription: 'What Makes up M·A·C. M·A·C is the world’s leading professional makeup authority because of our unrivalled expertise in makeup ARTISTRY. M·A·C is at the forefront of fashion TRENDSETTING, collaborating with leading talents from fashion, art and popular culture. Our Artists create trends backstage at fashion weeks around the world.',
        historyTitle:'Our History -> Birth of a Cult: From Wow to Now!',
        historyContent:'All Ages, All Races, All Genders… A professional makeup brand setting trends backstage at fashion weeks around the world. Today, M·A·C means so many things to its millions of fans in every corner of the planet, but a global beauty phenomenon has to begin somewhere. Make-Up Art Cosmetics started life in Toronto, Canada. Makeup artist and photographer Frank Toskan and salon owner Frank Angelo became frustrated by the lack of makeup that photographed well, so they decided to create their own. At first, they made the cosmetics in their kitchen and sold them straight from the salon to fellow makeup artists, as well as models and photographers.',
        titleLeft:'Holiday Collections',
        subTitleLeft:'Best Price !!',
        descriptionLeft:'For two days only, take 50% off our limited-edition Fix+ Party Pack / Shiny Pretty Things. Yours for only $12 ($36 Value)! Plus, free shipping and gift wrap on all orders. No code needed. Discount applied in cart.SHOP NOW',
        diffReference:'See the Ghiradelli Difference',
        src: '/images/MACHolidayPack.jpg',
        titleRight:'M·A·C Event Hub', 
        descriptionRight:'Own the trends now, while they’re fresh off Instagram or the runway! Sit with an Artist to explore all of the season’s hottest makeup. In a luxe one-on-one appointment, create the looks popping up backstage, on social or in magazines – then make them your own. Also available for groups!',
        link1:'Careers',
        link2:'Contact Us',
        link3:'Global Site',
        LogoImage:'MACLogo.png',
        BannerRightImage: '/images/MACRightbar.jpg',
        BannerLeftImage:'/images/MACHolidayPack.jpg',
        historyImage:'/images/MACHistory.png',
       }
]

export default DataOverView